### ISSUE TITLE
2021-12-21 Peer-to-peer code review

### ISSUE THREAD

**Issue by vechicin** [qwibbler/Capstone-Js-and-Networking#24]
# Hey @qwibbler and @ivaan1992, good job so far! 💯 

## I have a couple of suggestions to have a better setup in this initial portion of your project:

- To fix your issue with the HTML file not rendering images you could consider adding the Copy Webpack Plugin to your webpack.config.js
- Don't forget to set up Babel so you can use the ES6 import/export features within the Jest testing environment. Follow [this](https://jestjs.io/docs/getting-started) link in order to get started 
- Consider using semantic tags in your HTML file, so maybe change the div tag to a ul

## Other than that your project looks like it's starting to have a really nice look to it, keep it up! 🤓

**Comment by qwibbler** [comment]
Done!
